import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-neutral-900 text-white 
        max-w-screen-sm m-auto`}
      >
        {children}
      </body>
    </html>
  );
}

/* <body> 에서  {inter.className} 를 

  {`${inter.className} bg-neutral-900 text-white max-w-screen-sm m-auto`}
      
로 고침 
-> 기본적으로 적용되는 것들 배경, text 스타일 등등..
*/
